### ISSUE TITLE
Under Plot Settings, the Diameter Range can only start with 0, nnn

### ISSUE THREAD

**Issue by thareUSGS** [LWATLINGTON02/CraterStats-Capstone#20]
Please see Diameter range input text box. I can only type in:
0, nnn
when I try to filter to
200, nnn
I get a "cannot convert float to NaN to integer.

![image](https://github.com/user-attachments/assets/906a7019-3208-4bdd-a72a-9cf75385c206)

**Comment by CadenTed** [comment]
Can you please let me know the configuration settings and data plot you had? I can't seem to recreate this error.

**Comment by thareUSGS** [comment]
Yes, I am having trouble repeating. But now I can't get the legend to show the crater range in the top right. I will see if I can get that working again, perhaps that is were the error was coming from. Meaning trying to print the crater range on the plot. Hold.

**Comment by CadenTed** [comment]
From my experience testing, the error happens when trying to access data points outside of the range of the points that are plotted. The Range legend option is only available for poisson, b-poisson, c-fit, and d-fit plot fits, which can be accessed on the plot settings tab

**Comment by ggmichael** [comment]
The units for the diameter range are km. Might be useful to label the box "Diameter range, km"
