### ISSUE TITLE
When I exit the application (Windows) I get an application crash

### ISSUE THREAD

**Issue by thareUSGS** [LWATLINGTON02/CraterStats-Capstone#21]
Anaconda installed.
Windows  11

File, close or top right "x", the application crashes.

**Comment by E-Palms** [comment]
Hello Trent,
I am testing different conditions to try to recreate this. I have a hunch that the error's presence is involved with the memory size of generated plots. Do you remember the number of image generations or the approximate run time of the session when this occurs?

Best,
Evan
