### ISSUE TITLE
enhancement: one commandline, map integer to string (e.g., -cs n)

### ISSUE THREAD

**Issue by thareUSGS** [LWATLINGTON02/CraterStats-Capstone#22]
I love the commandline string at the bottom of the GUI. However, many of the options are locked to using numbers. Can those show their mapped strings?

for example:
craterstats -ep 1 
would be good to show
craterstats -ep moon

or
craterstats -cs 5
would be good to show
craterstats -cs neukumivanov

This might be easy or could be very tricky. So, consider this an optional enhancement.

**Comment by CadenTed** [comment]
Possibly easy enhancement. Is there a list of all the abbreviations for the chronology systems? I was unsure on how to write the different abbreviations for the different systems like how to differentiate Moon, Neukum (1983) and Moon, Neukem et. al. (2001)

**Comment by ggmichael** [comment]
The chronology system names are taken from functions.txt which are read into the dict f in cli.main (sorry for the 1-letter name! I use them for brief scope variables)

The function decode_abbreviation() in cli.py decodes any abbreviation to an index. You could use this to expand back to the full name.

**Comment by CadenTed** [comment]
I was able to get abbreviations for all functions except Mars, Ivanov (2001) and Mercury, Le Feuvre and Wieczorek 2011 porous. Would either of you happen to know abbreviations for these two?

**Comment by ggmichael** [comment]
This is a problem with my decode_abbreviation function. "Mars, Ivanov (2001)" could be considered an abbreviation of "Mars, Neukum-Ivanov (2001)", as "Le Feuvre and Wieczorek 2011 porous" can be of "Le Feuvre and Wieczorek 2011 non-porous". I'll have to think of a way to deal with that. The intention was that you should be able to write anything unambiguous, e.g. NI01 or Moon83, and still get what you want. I didn't consider this case. 

You should still find them all in the dict f in cli.main.

I should add that I also very much like the reconstruction of the command line below. Especially if it will work both ways (i.e. you can also enter a command line to change the UI and plot). An advantage of this would be that the UI is more robust against future additions of functionality... you will be able to do most of the work in the UI and add an extra option in the command line if needed.

**Comment by ggmichael** [comment]
I fixed this to resolve ambiguous names in favour of the shortest. Thus MarsIvan01 will give "Mars, Ivanov (2001)", and you need to include a differing part to get the superset name, e.g. MarsNeukIvan01 or FW11np for "Le Feuvre and Wieczorek 2011 non-porous"

**Comment by CadenTed** [comment]
The command line string is now showing abbreviations rather than index numbers. I think the pip module might need to be updated for these abbreviations to work, I'm not 100% sure though.
