### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by ggmichael** [LWATLINGTON02/CraterStats-Capstone#26]
Hi guys!

Congratulations on a very nice piece of work! I know that many people will appreciate having a GUI for this software tool.

In the program title bar and 'about', you use the name 'CraterstatsIV' which might suggest it supersedes the current version, when it's a parallel work. I would propose that you keep a separate name for this software: 'Capstone' seems like an apt choice to me. In the 'about' I think it would be good to indicate the pypi version number of craterstats 3 in use, so that there is no confusion over which results should be comparable (calculation are sometimes updated).

I saw your online presentation - very nice! Of course, if you have any questions, you're welcome to email me.

cheers,
Greg

**Comment by E-Palms** [comment]
Thank you, Greg. We are glad you like the app! I agree with the name change and will work on that. I believe we set that as the title at the beginning of our capstone before the entire team clearly understood what the project entailed and it never got changed. I'll fix that immediately and look forward to your valuable feedback on testing our application!
