### ISSUE TITLE
browse button

### ISSUE THREAD

**Issue by ggmichael** [LWATLINGTON02/CraterStats-Capstone#27]
Win10

I tried to open one of my own files using the 'browse' button, but it caused an error. The source file window shows a path beginning '\\', i.e. without the drive letter for windows. I guess this leads to the file not being found.

**Comment by E-Palms** [comment]
Hi Greg, can you please tell me what the file type was when attempting your upload?

**Comment by ggmichael** [comment]
It was a .scc file. The same Pickering.scc file that's in the samples, but
from a different location on windows drive D.

Cheers,
Greg

**Comment by E-Palms** [comment]
Okay, I recreated your error on my Windows 10 system. I implemented a fix and tested it with multiple drives (internal and external). Let me know if it works on your end.

Best,
Evan

**Comment by ggmichael** [comment]
That works for me now - thanks!
