### ISSUE TITLE
overplots

### ISSUE THREAD

**Issue by ggmichael** [LWATLINGTON02/CraterStats-Capstone#29]
Normally, these two plots should show simultaneously, i.e. one over the other. The idea is that you can construct a more complex figure that shows several datasets and age estimates. The craterplot dictionaries are passed as a list into Craterplotset so that they are all drawn together.

![simultaneous_plots](https://github.com/user-attachments/assets/3dede3b8-2722-4c79-832d-1cce7d58cf13)

**Comment by CadenTed** [comment]
I believe this should fix it. Funny enough I had a function stopping this behavior from happening because I thought it was something wrong with our program. Let me know if there are any other issues with this functionality. A delete and duplicate button will be added soon.
