### ISSUE TITLE
save format

### ISSUE THREAD

**Issue by ggmichael** [LWATLINGTON02/CraterStats-Capstone#30]
This is just a suggestion - I've had changing thoughts on it myself.

The save format you have created is very similar to what was used by Craterstats2. But you'll note that if you want to record more than one overplot in a file, you need to deal with multiple plot structures/dictionaries.

While I still use this format for setting up the default options, I've started writing a '.cs' file together with the output of every command. This file contains the used command line options (with some line breaks to make it more readable). You can recreate any plot by typing craterstats -i plotname.cs [you may need to refer to the github code - I think it may not be in the pypi version yet] The advantage of this is that you can easily modify a complex plot without being faced with navigating a very long command line.

It might be easy for you to do it this way, too, since you're already recreating the command line.

I think, at some point, I will remove the .plt default format from my code.

**Comment by CadenTed** [comment]
I wasn't able to find a .cs file to reproduce this inside of the github repo, is there a specific folder it might be in? My only thought on this is that there might be a problem related to the filename since typically a '.cs' file if for the C# programming language. Though if you've been using it with no problems my thought can be disregarded.

**Comment by ggmichael** [comment]
There is no .cs file currently in the repo, but one should be created each
time you run a command with output. The code is in cli.main.

It seems there was a bug in the argument capture for the .cs in the distro version, but should be fixed now.

I later realised that .cs is used for C#. It probably shouldn't matter, but maybe I'll change for .cst
